[feat] 질문 기능 개발
Kernel360/f1-KernelSquare-backend pull request #10
Opened 2023-12-21 10:47 UTC by mooncw

## PR을 보내기 전에 확인해주세요!!
- [x] 컨벤션에 맞게 작성했습니다. 컨벤션 확인은 [여기](https://www.notion.so/3ab6391203024ffa8be3b414c511d60e?pvs=4)
- [x] 변경 사항에 대한 테스트를 했습니다.

## 관련 이슈
close: #5 

## 개요
> QnA 중 질문의 기본적인 CRUD 기능을 구현하기 위함

## 상세 내용
- API 명세서와 ERD 기준으로 CRUD를 위한 코드 작성과 함께 약간의 코드 리팩토링 진행
- 테스트는 서비스와 컨트롤러 정상 동작에 대한 것만 작성(에러 상황에 대한 테스트 x)

- 이 후, 코드 품질이나 다른 도메인 기능 개발에 따른 리팩토링이 필요한 부분은 있음

- 기능 구현을 위해 다른 도메인이지만 필요한 코드 또는 파일 추가
- data.sql을 통해 기능 동작 확인을 위한 최소한의 데이터를 넣음
- 이 data.sql은 테스트를 할 때 실행시키지 않기 위해 test.resources에 테스트용 application.yml 파일 추가

2023-12-22 00:49 UTC, fingersdanny commented on src/main/java/com/kernel360/kernelsquare/domain/question/dto/CreateQuestionRequest.java
> +    List<String> skills
들어오는 @RequestBody 객체에 대한 정보를 검증할 수도 있군요. 배워갑니다.

2023-12-22 07:20 UTC, Hju95 approved these changes
다른 도메인 건드릴 시 분리해서 올리셔주세요

2023-12-22 08:42 UTC, fingersdanny requested changes
리뷰 남긴거 확인 부탁드려요

2023-12-22 08:42 UTC, fingersdanny commented on src/main/java/com/kernel360/kernelsquare/domain/question/service/QuestionService.java
그 enum type을 다음과 같은 양식으로 통일하는게 좋을거 같아요.. ``QUESTION_NOT_FOUND`` 

더 나은 의견이 있으시다면 comment로 남겨주세요.

2023-12-22 08:42 UTC, fingersdanny commented on src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/QuestionServiceStatus.java
> +    QUESTION_DELETED(2144);
분리해주신거 아주 보기 좋은거 같아요 👍🏻

2023-12-22 08:42 UTC, fingersdanny commented on src/main/java/com/kernel360/kernelsquare/global/dto/PageResponse.java
저번에 찬욱님께서 말씀해주셨던대로 Generic을 T로 받으셔도 돼요! 다른 코드는 T로 받는 것으로 바꿨어요

2023-12-22 08:42 UTC, fingersdanny commented on src/test/java/com/kernel360/kernelsquare/domain/question/service/QuestionServiceTest.java
> +//        assertThat();
todo를 남겨주신건 좋은데 지금 당장 검증할때 사용하지 않을 주석은 지워주시는게 좋을것 같아요!

2023-12-26 03:07 UTC, mooncw commented on src/main/java/com/kernel360/kernelsquare/domain/question/controller/QuestionController.java
> +        return ResponseEntityFactory.toResponseEntity(QUESTION_FOUND, questionService.findQuestion(questionId));
아래껄로

2023-12-26 03:15 UTC, RossKWSang approved these changes
LGTM

2023-12-26 03:20 UTC, fingersdanny approved these changes

2023-12-26 03:26 UTC, merged