[bugfix] 로그인 응답 ROLE 정상적으로 보내주도록 보냄
Kernel360/f1-KernelSquare-backend pull request #109
Opened 2024-01-12 02:24 UTC by mooncw

## PR을 보내기 전에 확인해주세요!!
- [x] 컨벤션에 맞게 작성했습니다. 컨벤션 확인은 [여기](https://www.notion.so/3ab6391203024ffa8be3b414c511d60e?pvs=4)
- [x] 변경 사항에 대한 테스트를 했습니다.

## 관련 이슈
close: #108 

## 개요
> 프론트가 이해할 수 있는 문자열 형태로 보내주도록 하기 위함

## 상세 내용
- Authoriy객체 주소에서 Authoriy의 AuthorityType의 문자열을 보내주도록 LoginResponse 수정

2024-01-12 09:38 UTC, fingersdanny commented on src/main/java/com/kernel360/kernelsquare/domain/auth/dto/LoginResponse.java
>  			.toList();
```java
List<String> roles = member.getAuthorities().stream()
	.map(MemberAuthority::getAuthority)
	.map(Authority::getAuthorityType)
	.map(AuthorityType::getDescription)
	.toList();
```

이런 식으로 이미 있는 내부 메서드 사용하도록 바꿔야할 것 같아요

2024-01-12 09:39 UTC, fingersdanny requested changes
comment 확인해주세요

2024-01-12 09:39 UTC, RossKWSang approved these changes

2024-01-12 09:44 UTC, mooncw commented on src/main/java/com/kernel360/kernelsquare/domain/auth/dto/LoginResponse.java
>  			.toList();
반영했습니다.

2024-01-15 01:56 UTC, fingersdanny approved these changes

2024-01-15 01:57 UTC, merged