[feat] 질문 & 답변 & 로그인 시 정책에 따른 경험치 부여 & 레벨업
Kernel360/f1-KernelSquare-backend pull request #118
Opened 2024-01-16 06:37 UTC by RossKWSang

## PR을 보내기 전에 확인해주세요!!
- [ ] 컨벤션에 맞게 작성했습니다. 컨벤션 확인은 [여기](https://www.notion.so/3ab6391203024ffa8be3b414c511d60e?pvs=4)
- [ ] 변경 사항에 대한 테스트를 했습니다.

## 관련 이슈
close: #64 

## 개요
> 경험치 부여와 레벨업 로직을 서비스 레이어에 추가함

## 상세 내용
- 단순 레벨업 시 경험치 부여이므로 일일 횟수에 제한 없음
- 7일 연속 로그인, 30일 연속 로그인 가산점 없음
- 답변 랭킹에 따른 가산점 없음 (배치 작업과 함께 추가해야함)
- 현 레벨의 상한에 도달할 경우 레벨업 로직 추가

2024-01-16 22:11 UTC, mooncw commented on src/main/java/com/kernel360/kernelsquare/domain/member/service/MemberService.java
> +		entityManager.refresh(member);
이걸 해줘야 memberRepository.updateExperienceByDifference가 적용이 되는건가요?
그리고 entityManager로 데이터베이스에 반영하는 것이라면, 생성날짜와 수정날짜가 DB에 들어가나요?
그리고 Transactional 어노테이션은 안붙어도 되는건가요?

2024-01-16 22:11 UTC, mooncw commented on src/main/java/com/kernel360/kernelsquare/global/entity/BaseEntity.java
> +	}
test 코드 때문에 만드신건가요?
아니면 entityManager 관련 문제로 만드신건가요?

2024-01-16 23:50 UTC, fingersdanny commented on src/main/java/com/kernel360/kernelsquare/domain/answer/service/AnswerService.java
> +		memberService.updateMemberExperienceByAction(member, ExperiencePolicy.ANSWER_CREATED.getReward());
메서드 명으로 봐서는 답변 전체 조회인데 회원 경험치 수정 로직이 왜 들어가 있어야 하죠?

2024-01-17 00:01 UTC, fingersdanny commented on src/main/java/com/kernel360/kernelsquare/domain/member/service/MemberService.java
> +		if (memberExperience >= upperLimit) {
상한선이랑 현재 경험치가 같은 경우는 필요 없지 않을까요?

2024-01-17 00:07 UTC, fingersdanny commented on src/main/java/com/kernel360/kernelsquare/domain/answer/service/AnswerService.java
> +	private final MemberService memberService;
비즈니스 레이어가 여기까지 올라오지 말고 찾은 멤버에 대한 레벨을 변경 감지를 통해서 수정할 수 있도록 해야할 거 같아요

2024-01-17 00:11 UTC, fingersdanny commented on src/main/java/com/kernel360/kernelsquare/domain/member/repository/MemberRepository.java
> +	void updateExperienceByDifference(@Param("memberId") Long memberId, @Param("diffExp") Long diffExp);
위에서 레벨은 도메인안에 메서드를 두시고 여기서 레벨은 JPQL로 하신 특별한 이유가 있는건가요? 

개인적으로는 방법을 전자로 통일하는게 좋아보입니다.

쿼리로 수정하지말고 객체를 찾아서 그 값을 변경해야 해당 회원 데이터에 대한 일관성을 유지하기 쉽지 않을까요

2024-01-17 00:21 UTC, fingersdanny commented on src/main/java/com/kernel360/kernelsquare/domain/member/service/MemberService.java
> +			memberRepository.updateExperienceByValue(member.getId(), memberExperience - upperLimit);
쿼리를 날리고 수정된 회원 정보를 매번 반영하기 위해서 위에서도 flush를 하고 아래서도 save를 하신 것으로 판단이 되는데 

그러지 말고 처음부터 회원 객체 하나만 찾고 그 회원에 대한 정보를 회원 내부 메서드로 수정하는 편이 좋아보여요.

결국 레벨이나 경험치나 데이터 베이스에 저장되기는 하지만 그 정보를 변경하는 책임 자체는 회원 엔티티가 가지고 있고 그를 수정하는 편이 조금 더 객체 지향적이지 않을까 생각해봅니다.

이러한 이유로 회원 경험치 수정 메서드가 레포지토리에 있으면 결국 회원 경험치에 대한 정보는 해당 회원 객체 뿐만 아니라 회원 레포지토리에서 둘 다 접근 가능한 형태가 되어버리는데 이러면 해당 회원에 대한 경험치 데이터에 대한 일관성이 어디서 깨질지 모른다고 생각합니당,,

2024-01-17 00:24 UTC, fingersdanny commented on src/test/java/com/kernel360/kernelsquare/domain/member/repository/MemberRepositoryTest.java
> +@DataJpaTest
``@DataJpaTest``내부에 이미 ``@Transactional``이 존재합니다. 위의 중복된 어노테이션은 지우는게 나을 거 같아요.

2024-01-17 00:26 UTC, fingersdanny commented on src/main/java/com/kernel360/kernelsquare/global/entity/BaseEntity.java
이 코드는 회원 뿐만 아니라 많은 엔티티에서 상속받아 사용하기 때문에 고칠 때 다른 엔티티에 끼칠 영향도 생각해보는게 좋을거 같아요.

2024-01-17 00:29 UTC, fingersdanny commented on src/main/java/com/kernel360/kernelsquare/global/entity/BaseEntity.java
> +	}
``@DataJpaTest`` 하실 때 JpaAuditingConfig를 불러오지 않으면 위의 ``@CreatedDate``나 ``@LastModifiedDate`` 때문에 에러가 떠서 위처럼 바꾸신 걸로 짐작이 되는데,,

위는 테스트 클래스에서 ``@Import(JpaAuditingConfig)``를 불러와서 해결할 수 있어요.

테스트 진행 시는 실제 운영 코드를 바꾸는 것을 최대한 지향하고 가능하다면 실제 코드를 테스트 할 수 있도록 위와 같은 변경 점을 줄이는게 좋아요. 테스트 때문에 운영 코드를 바꿔야한다면 그때부터 "테스트"의 의미가 사라지니까요

2024-01-17 00:34 UTC, fingersdanny commented on src/test/java/com/kernel360/kernelsquare/domain/question/service/QuestionServiceTest.java
완성되지 않은 테스트인..가요?

2024-01-17 00:36 UTC, fingersdanny commented on src/test/java/com/kernel360/kernelsquare/domain/member/repository/MemberRepositoryTest.java
> +    private Level level_02;
Java Naming Convention에 맞게 변수명을 바꾸어주세요, [여기](https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html)서 보시면 됩니당

2024-01-17 00:40 UTC, fingersdanny commented on src/main/java/com/kernel360/kernelsquare/global/util/experience/ExperiencePolicy.java
더 추가될 경험치 로직이 있어서 인터페이스를 구현하는 방식으로 작성하신건가요?

2024-01-17 00:43 UTC, fingersdanny requested changes
Comment 확인하시고 같이 얘기해보고 싶은게 있다면 알려주세요

2024-01-18 01:39 UTC, fingersdanny commented on src/main/java/com/kernel360/kernelsquare/domain/answer/service/AnswerService.java
> +			Level nextLevel = levelRepository.findByName(member.getLevel().getName() + 1)
이건 진짜 "광야"네요

2024-01-18 01:43 UTC, fingersdanny commented on src/main/java/com/kernel360/kernelsquare/domain/answer/service/AnswerService.java
>  	public List<FindAnswerResponse> findAllAnswer(Long questionId) {
이제 보니까 다른 곳은 ``FindAllLevelResponse``나 ``FindAllTechStackResponse``처럼 하고 있는데 이렇게 수정하는 건 어떨까요?

2024-01-18 01:50 UTC, fingersdanny commented on src/main/java/com/kernel360/kernelsquare/domain/auth/service/AuthService.java
> +	}
인증 서비스에 갑자기 이 메서드가 생긴 이유가 있을까요?

2024-01-18 01:53 UTC, fingersdanny commented on src/main/java/com/kernel360/kernelsquare/domain/member/entity/Member.java
>  import jakarta.persistence.*;
회원 엔티티에 BusinessException 있어야할 이유가... 있나요?

2024-01-18 01:55 UTC, fingersdanny requested changes
Comment 확인해주세요.

2024-01-18 02:03 UTC, fingersdanny commented on src/test/java/com/kernel360/kernelsquare/domain/answer/service/AnswerServiceTest.java
> +	private MemberService memberService;
이 라인 없어야 할것 같아요!

2024-01-18 02:04 UTC, fingersdanny commented on src/test/java/com/kernel360/kernelsquare/domain/auth/service/AuthServiceTest.java
> +
요기도 지우셔야할 것 같습니다.

2024-01-18 02:06 UTC, Hju95 commented on src/main/java/com/kernel360/kernelsquare/global/entity/BaseEntity.java
> +public abstract class BaseEntity {
바꾸신 이유가 있나요?

2024-01-18 02:09 UTC, fingersdanny commented on src/main/java/com/kernel360/kernelsquare/global/entity/BaseEntity.java
> +import org.hibernate.annotations.ColumnDefault;
헉 이것도,, 지워주세요~

2024-01-18 02:10 UTC, Hju95 approved these changes
👍

2024-01-18 02:19 UTC, fingersdanny commented on src/main/java/com/kernel360/kernelsquare/domain/answer/service/AnswerService.java
>  	public List<FindAnswerResponse> findAllAnswer(Long questionId) {
@RossKWSang

2024-01-18 02:20 UTC, fingersdanny commented on src/test/java/com/kernel360/kernelsquare/domain/question/service/QuestionServiceTest.java
>      Level level;
private.. 해주세요?

2024-01-18 05:48 UTC, fingersdanny reviewed
진짜 고생많으셨습니당,,,

2024-01-18 05:49 UTC, fingersdanny approved these changes

2024-01-18 05:49 UTC, merged