[refactor] 예약창 생성 로직 리팩터링
Kernel360/f1-KernelSquare-backend pull request #121
Opened 2024-01-18 11:35 UTC by Hju95

## PR을 보내기 전에 확인해주세요!!
- [x] 컨벤션에 맞게 작성했습니다. 컨벤션 확인은 [여기](https://www.notion.so/3ab6391203024ffa8be3b414c511d60e?pvs=4)
- [x] 변경 사항에 대한 테스트를 했습니다.

## 관련 이슈
close: #85 

## 개요
> 예약창 생성 로직 리팩터링

## 상세 내용
- 예약창 생성 시 hashtag, chatroom, reservation 동시에 생성
- Flyway 컬럼 및 데이터 추가
- 테스트 확인 완료

2024-01-18 11:55 UTC, mooncw requested changes
ㅇㅂㅇ

2024-01-18 11:55 UTC, mooncw commented on src/main/resources/db/migration/V1.2__add_initial_data.sql
> +    `finished`               BOOLEAN DEFAULT FALSE,
tinyint ㄱ

2024-01-18 11:55 UTC, mooncw commented on src/main/resources/db/migration/V1.3__add_table.sql
> +    `room_name` varchar(20) COLLATE utf8mb4_unicode_ci,
DEFAULT NULL 필요한가요?

2024-01-18 11:55 UTC, mooncw commented on src/main/resources/db/migration/V1.3__add_table.sql
> +VALUES (now(), 1, 'test_room_key', null, null, 0);
modified_date도 created_date와 같은 값으로 넣어주세요

2024-01-19 01:19 UTC, RossKWSang approved these changes

2024-01-19 01:37 UTC, Hju95 commented on src/main/resources/db/migration/V1.3__add_table.sql
> +    `room_name` varchar(20) COLLATE utf8mb4_unicode_ci,
코드 통일성을 위해 추가했습니다.

2024-01-19 01:41 UTC, Hju95 commented on src/main/resources/db/migration/V1.2__add_initial_data.sql
> +    `finished`               BOOLEAN DEFAULT FALSE,
반영했습니다.

2024-01-19 01:41 UTC, Hju95 commented on src/main/resources/db/migration/V1.3__add_table.sql
> +VALUES (now(), 1, 'test_room_key', null, null, 0);
반영했습니다.

2024-01-19 01:44 UTC, mooncw approved these changes
ㄱㄱ

2024-01-19 01:44 UTC, merged