[bugfix] 회원 정보 수정 API 분리
Kernel360/f1-KernelSquare-backend pull request #159
Opened 2024-01-26 08:02 UTC by RossKWSang

## PR을 보내기 전에 확인해주세요!!
- [x] 컨벤션에 맞게 작성했습니다. 컨벤션 확인은 [여기](https://www.notion.so/3ab6391203024ffa8be3b414c511d60e?pvs=4)
- [x] 변경 사항에 대한 테스트를 했습니다.

## 관련 이슈
close: #158 

## 개요
> 회원 소개 변경 시 프로필이 Null로 바뀌는 버그 수정
> API를 분리하여 관련 문제가 없도록 만듬
> 이슈에 관련된 설명

## 상세 내용
- 회원 정보 수정을 회원 프로필 수정과 회원 소개 수정으로 바꾸고 응답 상태 코드를 업데이트
- 소개변경 API : member/{memberId}/introduction
- 프로필변경 API : member/{memberId}/profile
  - API 명세서
    - https://www.notion.so/API-0dd89c67c2af4c2abedcc4712f8e627e
  - 응답상태코드
    - https://www.notion.so/c54aec9cd60e47078d0d321b0472ae09

2024-01-26 08:11 UTC, mooncw commented on src/main/java/com/kernel360/kernelsquare/domain/member/controller/MemberController.java
> +		@RequestBody UpdateMemberIntroductionRequest updateMemberIntroductionRequest) {
@Valid를 붙여주셔야 UpdateMemberIntroductionRequest의 @NotBlank가 적용됩니다.

2024-01-26 08:11 UTC, RossKWSang commented on src/main/java/com/kernel360/kernelsquare/domain/member/controller/MemberController.java
> +		@RequestBody UpdateMemberIntroductionRequest updateMemberIntroductionRequest) {
오 감사합니다.

2024-01-26 08:12 UTC, mooncw commented on src/main/java/com/kernel360/kernelsquare/domain/member/dto/UpdateMemberIntroductionRequest.java
> +	@NotBlank
message 도 넣어주시고, 그에 대한 테스트를..?

2024-01-26 08:14 UTC, RossKWSang commented on src/main/java/com/kernel360/kernelsquare/domain/member/dto/UpdateMemberIntroductionRequest.java
> +	@NotBlank
추후 반영하겠습니다.

2024-01-26 08:23 UTC, mooncw approved these changes
ㄱㄱ

2024-01-29 01:41 UTC, fingersdanny requested changes
지금 클라이언트에서 수정 요청 받을 때 

```
{
    introduction : "~~~~",
    image_url : "null"
}
```

이렇게 받아오나요?

2024-01-29 02:25 UTC, mooncw commented
> 지금 클라이언트에서 수정 요청 받을 때
> 
> ```
> {
>     introduction : "~~~~",
>     image_url : "null"
> }
> ```
> 
> 이렇게 받아오나요?

2024-01-29 02:25 UTC, mooncw commented
잘못 눌러서 풀리퀘 닫아서버려서 재오픈했습니다 ;

2024-01-29 04:37 UTC, RossKWSang commented
> 지금 클라이언트에서 수정 요청 받을 때
> 
> ```
> {
>     introduction : "~~~~",
>     image_url : "null"
> }
> ```
> 
> 이렇게 받아오나요?

프로필을 저장하고 자기소개를 변경한 이후

받아온 멤버 데이터가 다음과 같습니다

![image](https://github.com/Kernel360/f1-KernelSquare-backend/assets/92242326/8f4ce7d0-e36a-4cf9-9f22-adc656e3a519)

2024-01-29 05:04 UTC, fingersdanny commented
응답 말고 요청을 어떤 식으로 넣는지 알려주세요

2024-01-29 06:33 UTC, fingersdanny approved these changes
LGTM

2024-01-29 06:33 UTC, merged