[feat] 예약창 조회 리팩터링 & 예약창 수정
Kernel360/f1-KernelSquare-backend pull request #163
Opened 2024-01-29 09:08 UTC by Hju95

## PR을 보내기 전에 확인해주세요!!
- [x] 컨벤션에 맞게 작성했습니다. 컨벤션 확인은 [여기](https://www.notion.so/3ab6391203024ffa8be3b414c511d60e?pvs=4)
- [ ] 변경 사항에 대한 테스트를 했습니다.

## 관련 이슈
close: #87 

## 개요
> 예약창 요구사항 반영하여 리팩터링 & 예약창 수정 기능 구현

## 상세 내용
- 예약창 조회 리팩터링 - 채팅방과 연계하여 로직 수정
- 예약창 최대 수, 최대 기간 체크 로직
- 포스트맨 테스트 완료
- 특이사항 :멀티모듈 이후 테스트 코드 작성

2024-01-29 09:28 UTC, fingersdanny commented on src/main/java/com/kernel360/kernelsquare/domain/hashtag/dto/UpdateHashtagRequest.java
> +        @NotBlank(message = "add 혹은 remove 가 필요합니다.")
조금 더 명시적인 메시지가 낫지 않을까요? 
``상태 값이 필요합니다`` 는 어떻게 생각하시나요?

2024-01-29 09:31 UTC, fingersdanny commented on src/test/java/com/kernel360/kernelsquare/domain/reservation_article/service/ReservationArticleServiceTest.java
> +        given(reservationRepository.findAllByReservationArticleId(anyLong())).willReturn(List.of(testReservation));
주석 처리된 코드가 필요한 이유가 있을까요?

2024-01-29 09:32 UTC, fingersdanny commented on src/main/java/com/kernel360/kernelsquare/global/config/SecurityConfig.java
여기 줄 바꿈이.. 이상하네요

2024-01-29 09:42 UTC, fingersdanny commented on src/main/java/com/kernel360/kernelsquare/domain/reservation/dto/UpdateReservationRequest.java
> +        @NotBlank(message = "add 혹은 remove 가 필요합니다.")
동일한 내용으로 조금 더 명시적으로 메시지를 수정하시는게 어떨까 생각합니다.

2024-01-29 09:47 UTC, fingersdanny commented on src/main/java/com/kernel360/kernelsquare/domain/reservation_article/service/ReservationArticleService.java
> +        return FindReservationArticleResponse.of(member, reservationArticle, findHashtagResponses, findReservationResponses, member.getLevel());
이거 받는 인자 줄일 수 있을거 같아요!!!! DTO 내부에서 다른 엔티티들을 불러오도록 수정해주세요

2024-01-29 09:47 UTC, fingersdanny requested changes
~반려~ 코멘트 확인 부탁드려요!

2024-01-30 02:02 UTC, RossKWSang approved these changes

2024-01-30 02:02 UTC, RossKWSang commented on src/main/java/com/kernel360/kernelsquare/domain/reservation_article/service/ReservationArticleService.java
> +                .orElseThrow(() -> new BusinessException(ReservationArticleErrorCode.RESERVATION_ARTICLE_NOT_FOUND));
한 메서드에 많은 로직이 있는 것 같으니 나중에 리펙터링을 하는게 좋을 것 같습니다.

2024-01-30 04:25 UTC, Hju95 commented on src/main/java/com/kernel360/kernelsquare/domain/hashtag/dto/UpdateHashtagRequest.java
> +        @NotBlank(message = "add 혹은 remove 가 필요합니다.")
반영했습니다.

2024-01-30 04:26 UTC, Hju95 commented on src/test/java/com/kernel360/kernelsquare/domain/reservation_article/service/ReservationArticleServiceTest.java
> +        given(reservationRepository.findAllByReservationArticleId(anyLong())).willReturn(List.of(testReservation));
지웠습니다.

2024-01-30 04:26 UTC, Hju95 commented on src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/ReservationArticleServiceStatus.java
> +
공백도 지웠습니다.

2024-01-30 04:27 UTC, Hju95 commented on src/main/java/com/kernel360/kernelsquare/domain/reservation/dto/UpdateReservationRequest.java
> +        @NotBlank(message = "add 혹은 remove 가 필요합니다.")
동일하게 반영했습니다.

2024-01-30 04:27 UTC, Hju95 commented on src/main/java/com/kernel360/kernelsquare/domain/reservation_article/service/ReservationArticleService.java
> +        return FindReservationArticleResponse.of(member, reservationArticle, findHashtagResponses, findReservationResponses, member.getLevel());
수정하고 테스트 코드도 수정 완료했습니다.

2024-01-30 04:28 UTC, Hju95 commented on src/main/java/com/kernel360/kernelsquare/domain/reservation_article/service/ReservationArticleService.java
> +                }
예외처리 추가하였습니다.

2024-01-30 04:28 UTC, Hju95 commented on src/main/java/com/kernel360/kernelsquare/domain/reservation_article/service/ReservationArticleService.java
> +                .orElseThrow(() -> new BusinessException(ReservationArticleErrorCode.RESERVATION_ARTICLE_NOT_FOUND));
넵 추후 반영하겠습니다.

2024-01-30 06:18 UTC, fingersdanny approved these changes
good

2024-01-30 06:19 UTC, merged