Feature/#257 image limit
Kernel360/f1-KernelSquare-backend pull request #259
Opened 2024-02-19 07:34 UTC by mooncw

## PR을 보내기 전에 확인해주세요!!
- [x] 컨벤션에 맞게 작성했습니다. 컨벤션 확인은 [여기](https://www.notion.so/3ab6391203024ffa8be3b414c511d60e?pvs=4)
- [x] 변경 사항에 대한 테스트를 했습니다.

## 관련 이슈
close: #257 

## 개요
> 이미지 검증 로직이 없기에 추가하기 위함

## 상세 내용
- 크기 제한 예외처리는 GlobalExceptionHandler에서 처리 -> 추후 BusinessException 아닌 예외처리는 리팩토링 필요해보임
- 확장자 검증 로직 추가

2024-02-19 10:01 UTC, RossKWSang approved these changes

2024-02-19 10:03 UTC, Hju95 commented on core/src/main/java/com/kernelsquare/core/common_response/error/GlobalExceptionHandler.java
> +	}
저도 궁금합니다

2024-02-19 10:40 UTC, mooncw commented on core/src/main/java/com/kernelsquare/core/common_response/error/GlobalExceptionHandler.java
> +	}
반환 예외 객체가 다르기 때문입니다.
추후 이 부분과 윗 부분은 리팩토링 예정입니다.

2024-02-19 14:10 UTC, fingersdanny commented on core/src/main/java/com/kernelsquare/core/common_response/error/GlobalExceptionHandler.java
> +	}
추후에 리팩토링 하지 마시고 지금 PR에 수정해서 올려주세요.

2024-02-19 14:11 UTC, fingersdanny commented on core/src/main/java/com/kernelsquare/core/type/ImageExtensionType.java
> +        return Arrays.stream(ImageExtensionType.values()).map(ImageExtensionType::getExtension).toList();
https://inpa.tistory.com/entry/JAVA-%E2%98%95-ArraysasList-%EC%99%80-Listof-%EC%B0%A8%EC%9D%B4-%ED%95%9C%EB%B0%A9-%EC%A0%95%EB%A6%AC

2024-02-19 14:12 UTC, fingersdanny requested changes
리뷰 확인 부탁드려요

2024-02-19 14:42 UTC, mooncw commented on core/src/main/java/com/kernelsquare/core/type/ImageExtensionType.java
> +        return Arrays.stream(ImageExtensionType.values()).map(ImageExtensionType::getExtension).toList();
이렇게까지 알고 쓴 건 아니지만, toList가 맞아보입니다.
호옥시 병룡님은 다른 생각이신가요?

2024-02-20 02:51 UTC, mooncw commented on core/src/main/java/com/kernelsquare/core/common_response/error/GlobalExceptionHandler.java
> +	}
보완을 했는데, 확인해주시고 피드백 좀 부탁드립니다 ㅎㅎ..

2024-02-20 04:04 UTC, fingersdanny commented on core/src/main/java/com/kernelsquare/core/type/ImageExtensionType.java
> +        return Arrays.stream(ImageExtensionType.values()).map(ImageExtensionType::getExtension).toList();
저도 같은 생각입니다. 해당 리스트가 나중에 변환될 필요는 없어 보입니다! 👍🏻

2024-02-20 05:50 UTC, Hju95 approved these changes

2024-02-20 06:15 UTC, fingersdanny commented on core/src/main/java/com/kernelsquare/core/common_response/ResponseEntityFactory.java
> +	}
저도 RuntimeException을 예외 처리하는거에 조금 더 생각해봤었는데 저희가 들었던 강의에서도 그렇고 다른 팀에서는 Exception을 처리해서 서버 예외를 처리하더라고요..?

제가 이미 여러번 보내서 이미 잘 알고 계시겠지만, https://devlog-wjdrbs96.tistory.com/351

요기를 보시면 RuntimeException을 상속받는 친구들은 UncheckedException이라서 명시적인 예외처리를 해주지 않아도 되지만, 그 외의 예외(CheckedException) 가 터졌을 때 클라이언트 단에서 알 수 있는 방법이 없고 해당 예외들에 대한 로깅또한 할 수 없을 거라는 생각이들어서 Exception을 처리하는 방향으로 수정해보는 것도 괜찮은 방법이라 생각이 드는데.. 어떻게 생각하시나요?

2024-02-20 06:16 UTC, fingersdanny commented on core/src/main/java/com/kernelsquare/core/common_response/error/GlobalExceptionHandler.java
> +	}
``ResponseEntityFactory``에 남긴 리뷰를 확인하시고 생각을 알려주세요!

2024-02-20 06:16 UTC, fingersdanny requested changes
예외처리에 대한 여러분 생각이 듣고 싶어요. @mooncw @Hju95 @RossKWSang

2024-02-20 06:18 UTC, RossKWSang commented on core/src/main/java/com/kernelsquare/core/common_response/ResponseEntityFactory.java
> +	}
CheckedException은 컴파일 예외라고 알고있는데 이런 예외가 존재해도 빌드가 되나요?

2024-02-20 07:29 UTC, fingersdanny commented on core/src/main/java/com/kernelsquare/core/common_response/ResponseEntityFactory.java
> +	}
빌드 이후에도 외부 리소스와 연결 과정 중에서 checkedException이 발생할 수 있다고 알고 있어서..말씀하신거처럼 빌드는 되지 않습니다.

2024-02-20 07:53 UTC, mooncw commented on core/src/main/java/com/kernelsquare/core/common_response/error/GlobalExceptionHandler.java
> +	}
다시 생각해보니 실행 중이던 애플리케이션에서 checkedException인 SQLException이 발생했던 기억이 있어서 Exception을 처리하는 방향이 맞는거 같습니다.

2024-02-20 08:07 UTC, Hju95 commented on core/src/main/java/com/kernelsquare/core/common_response/ResponseEntityFactory.java
> +	}
Checked Exception이 발생하는 시점은 다음과 같습니다:

파일 입출력(IO) 작업 중에 발생할 수 있는 IOException
데이터베이스 접근 중에 발생할 수 있는 SQLException
네트워크 통신 중에 발생할 수 있는 예외들

찬욱님이랑 같이 봤던 런타임 중 SQLException 입니다.

<img width="721" alt="스크린샷 2024-02-06 오전 3 41 50" src="https://github.com/Kernel360/f1-KernelSquare-backend/assets/59231743/c8084ad0-9978-453e-ad22-fec0089986d8">

Exception 처리하는 방향으로 수정하시는 것에 대해 동의합니다.

2024-02-21 00:25 UTC, fingersdanny commented
> 예외처리에 대한 여러분 생각이 듣고 싶어요. @mooncw @Hju95 @RossKWSang

예외 처리에 대해 어느 정도 결론이 난 거 같으니 Exception을 처리하는 방향으로 수정해주세요!

2024-02-21 01:19 UTC, mooncw commented
Exception 처리하는 방향으로 변경했습니다.

2024-02-21 01:35 UTC, fingersdanny commented on core/src/main/java/com/kernelsquare/core/common_response/ResponseEntityFactory.java
> +	}
😄 일단은 지금 변경된 사항처럼 진행해도 괜찮을 듯 합니다

2024-02-21 08:31 UTC, merged