[bug] 예약창 시간 제한 추가 & 예약창 리포지토리 테스트 추가
Kernel360/f1-KernelSquare-backend pull request #262
Opened 2024-02-19 11:00 UTC by RossKWSang

## PR을 보내기 전에 확인해주세요!!
- [ ] 컨벤션에 맞게 작성했습니다. 컨벤션 확인은 [여기](https://www.notion.so/3ab6391203024ffa8be3b414c511d60e?pvs=4)
- [ ] 변경 사항에 대한 테스트를 했습니다.

## 관련 이슈
close: #261 

## 개요
> 예외 메시지를 추가하고 예약창 생성을 현재 앞서고 있는 예약의 Endtime이 없을 경우에만 생성할 수 있도록 하였습니다.

## 상세 내용
- 추가로 테스트 코드가 없는 예약창 리포지토리 메서드는 테스트 코드를 추가하였습니다.

2024-02-19 11:03 UTC, mooncw commented on domain-mysql/src/test/java/com/kernelsquare/domainmysql/domain/level/repository/LevelRepositoryTest.java
> +@DisplayName("레벨 레포지토리 단 테스트")
'위'

2024-02-19 11:05 UTC, RossKWSang commented on domain-mysql/src/test/java/com/kernelsquare/domainmysql/domain/level/repository/LevelRepositoryTest.java
> +@DisplayName("레벨 레포지토리 단 테스트")
바꿨습니다

2024-02-19 11:06 UTC, mooncw commented on domain-mysql/src/test/java/com/kernelsquare/domainmysql/domain/reservation/repository/ReservationRepositoryTest.java
> +    }
testStartTime과 testExpireTime이 같은 이유와 createTestReservation에 testExpireTime이 아닌 testStartTime.plusMinutes(30L)으로 하신 이유가 뭘까요?

2024-02-19 11:09 UTC, RossKWSang commented on domain-mysql/src/test/java/com/kernelsquare/domainmysql/domain/reservation/repository/ReservationRepositoryTest.java
> +    }
testExpireTime은 ChatRoom에 들어가는 LocalDateTime객체로 더미 데이터 정도로만 생각했습니다.
그런데 논리적으로 예약 생성의 EndTime과 동일한게 좋겠네요.
반영하겠습니다.

2024-02-19 11:17 UTC, mooncw commented on member-api/src/test/java/com/kernelsquare/memberapi/domain/reservation_article/service/ReservationArticleServiceTest.java
> +		);
anyLong()과 eq(member.getId())의 차이점이 뭔가요?
ReservationArticleServiceTest에서 만든 member id만 들어갈 수 있다는 건가요?

2024-02-19 14:15 UTC, fingersdanny requested changes
리뷰 확인해 주세요.

2024-02-20 01:06 UTC, Hju95 commented on core/src/main/java/com/kernelsquare/core/common_response/error/code/ReservationArticleErrorCode.java
> +			"현재 끝나지 않은 커피챗 예약을 지닌 예약창이 있습니다.");
이미 예약창이 있습니다
로 해도 되지 않을까요?

2024-02-20 05:49 UTC, Hju95 approved these changes

2024-02-20 05:55 UTC, mooncw approved these changes
승인

2024-02-20 06:16 UTC, Hju95 approved these changes

2024-02-20 06:24 UTC, fingersdanny reviewed
코드 리뷰... 확인해주세요

2024-02-20 07:30 UTC, fingersdanny commented on domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/reservation/repository/ReservationRepository.java
> +	Boolean existsByMemberIdAndFinishedIsFalseAndEndTimeAfter(Long memberId, LocalDateTime currentTime);
그것도 좋아보이네요~

2024-02-21 08:32 UTC, fingersdanny approved these changes
LGTM

2024-02-21 08:32 UTC, merged