[refactor] 채팅 중복 체크 로직 추가 및 채팅방 멤버 리스트 관리 로직 추가
Kernel360/f1-KernelSquare-backend pull request #287
Opened 2024-02-22 11:57 UTC by mooncw

## PR을 보내기 전에 확인해주세요!!
- [x] 컨벤션에 맞게 작성했습니다. 컨벤션 확인은 [여기](https://www.notion.so/3ab6391203024ffa8be3b414c511d60e?pvs=4)
- [x] 변경 사항에 대한 테스트를 했습니다.

## 관련 이슈
close: #272 

## 개요
> 중복 입장을 제한하고 채팅방의 멤버 리스트를 관리하기 위함

## 상세 내용
- 채팅방을 관리하는 ChatRoomMemberManager 추가
- stomp 메시지에서 필요한 데이터를 추출하기 위한 StompMessageParser 추가
- stomp 메시지 command에 따라 채팅방 조작하는 StompHandler 추가
- 소켓 통신 테스트 x (일단 주석 처리했고 없앨지 말지 이야기 합시다.)
- 실제 프론트에서 작동 되는지 확인해야 함

2024-02-22 11:58 UTC, mooncw commented
인원 제한 로직을 깜박해서 추가하고 다시 push 하겠습니다..

2024-02-22 12:31 UTC, mooncw commented
인원 제한 로직 추가 했습니다. 리뷰 해주십셔

2024-02-22 12:42 UTC, mooncw commented
프론트 로직이 완성되면 맞춰보고 merge 해야할 것 같습니다.

2024-02-26 02:03 UTC, Hju95 commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/component/ChatRoomMemberManager.java
> +    private final ConcurrentHashMap<String, List<ChatRoomMember>> chatRoomMap = new ConcurrentHashMap<>();
동시에 입장해서 멤버목록을 관리한다고 하면 List 보다 Collections.synchronizedList 를 고려해봐도 좋을 것 같습니다.
물론 지금은 2명 입장이라 괜찮을 것 같지만 그룹으로 확대된다고 했을 때를 생각해보면 한번 고민해봐도 좋을 것 같네요.

2024-02-26 02:06 UTC, Hju95 commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/component/ChatRoomMemberManager.java
> +            .get();
예기치 못하게 멤버목록이 리스트에 들어가지도 못했는데 삭제하기 위해 찾을 경우
NoSuchElementException 에러가 떨어질 수도 있지 않을까요? 예외처리 로직은 안전하게 있어야하지 않을까 싶습니다.

2024-02-26 02:14 UTC, Hju95 commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/component/StompMessageParser.java
> +            return destinationSplit[destinationSplit.length - 1];
코드 가독성을 위해 
`return destinationSplit[destinationSplit.length - 1];`
`return lastDestination; `같이 적어주는 게 좋지 않을까 합니다.

2024-02-26 02:15 UTC, Hju95 commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/dto/FindMongoChatMessage.java
> +
변수들 사이에 공백 지워주세요..

2024-02-26 02:17 UTC, Hju95 commented
채팅 관련 부분은 메서드에 간단한 주석으로 역할 정도만 적어주면 좋겠다는 의견이 있습니다..ㅜ

2024-02-26 02:18 UTC, fingersdanny commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/component/ChatRoomMemberManager.java
> +            .get();
member null 체크를 해야할 듯 합니당

2024-02-26 02:19 UTC, fingersdanny commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/component/StompMessageParser.java
> +            return destinationSplit[destinationSplit.length - 1];
아니면 그냥 스트림..으로 할 수도 있지 않을까요

2024-02-26 02:20 UTC, fingersdanny commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/dto/FindMongoChatMessage.java
> +
쓱삭 쓱삭

2024-02-26 02:22 UTC, fingersdanny reviewed
리뷰 확인 부탁드려요~

2024-02-26 02:25 UTC, mooncw commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/component/ChatRoomMemberManager.java
> +    private final ConcurrentHashMap<String, List<ChatRoomMember>> chatRoomMap = new ConcurrentHashMap<>();
멤버 목록은 ConcurrentHashMap 안에 있기 때문에 List여도 상관없다고 생각했는데, 다른 분들의 생각은 어떠신가요?

2024-02-26 02:45 UTC, mooncw commented
> 채팅 관련 부분은 메서드에 간단한 주석으로 역할 정도만 적어주면 좋겠다는 의견이 있습니다..ㅜ

커찮..

2024-02-26 03:51 UTC, mooncw commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/component/ChatRoomMemberManager.java
> +            .get();
추가 했습니다.

2024-02-26 03:51 UTC, mooncw commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/component/StompMessageParser.java
> +            return destinationSplit[destinationSplit.length - 1];
null 체크도 추가하여 반영했습니다.

2024-02-26 03:52 UTC, mooncw commented
추가적으로 stomp 소켓 테스트 삭제하겠습니다.

2024-02-26 05:06 UTC, fingersdanny commented
> 추가적으로 stomp 소켓 테스트 삭제하겠습니다.

잘 가요,, 이젠 보내줍시다...

2024-02-26 08:49 UTC, mooncw commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/dto/FindMongoChatMessage.java
> +
쓱삭 쓱삭

2024-02-26 08:51 UTC, Hju95 approved these changes

2024-02-26 08:52 UTC, Hju95 requested changes
__아직은 안돼요

2024-03-07 08:04 UTC, RossKWSang commented
이 PR은 왜 계속 남아있나요?

2024-03-08 01:06 UTC, fingersdanny commented
> 이 PR은 왜 계속 남아있나요?
이거 무슨 프론트랑 안 맞춰보면 머지 못하는 pr이었던것 같아요..

@RossKWSang

2024-03-08 01:14 UTC, mooncw commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/component/ChatRoomMemberManager.java
> +            .get();
해당 코드가 삭제되었습니다.

2024-03-08 03:35 UTC, mooncw commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/component/ChatRoomMemberManager.java
> +    private final ConcurrentHashMap<String, List<ChatRoomMember>> chatRoomMap = new ConcurrentHashMap<>();
List 대신 CopyOnWriteArraySet를 사용했습니다.

2024-03-09 09:27 UTC, Hju95 approved these changes

2024-03-19 13:46 UTC, fingersdanny commented
이 친구.. 언제쯤 머지되나요..? @mooncw

2024-03-20 05:16 UTC, mooncw commented
로직 변경이 필요해져서 close하고 변경이 되면 다시 reopen 하겠습니다.
@fingersdanny

2024-03-20 05:16 UTC, closed without merging