[feat] 알림 기능 추가
Kernel360/f1-KernelSquare-backend pull request #307
Opened 2024-02-29 10:27 UTC by mooncw

## PR을 보내기 전에 확인해주세요!!
- [x] 컨벤션에 맞게 작성했습니다. 컨벤션 확인은 [여기](https://www.notion.so/3ab6391203024ffa8be3b414c511d60e?pvs=4)
- [x] 변경 사항에 대한 테스트를 했습니다.

## 관련 이슈
close: #294 

## 개요
> 답변을 작성할 때 질문의 작성자에게 알림이 가는 기능과 매일 오전 2시에 랭킹이 매겨진 답변들의 작성자에게 알림을 보내기 위함

## 상세 내용
- Alert 도메인을 추가
- 추가하면서 엮여있는 로직들과 함께 리팩토링
- SSE를 사용
- 매일 오전 2시에 동작하는 것은 `@Scheduler` 로 동작
- 알림 로직은 `@Async` 를 사용하여 비동기로 동작
- 알림은 MongoDB에 저장

2024-02-29 13:18 UTC, mooncw commented on domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/member_answer_vote/repository/MemberAnswerVoteReader.java
> +    Boolean existsByMemberIdAndAnswerId(Long memberId, Long answerId);
메서드명 추천 받습니다.

2024-02-29 13:31 UTC, mooncw commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/dto/RankAnswerAlertMessage.java
> +            .senderId("system")
"system"을 넣는거 말고 더 좋은 방법 있을까요?

2024-02-29 13:41 UTC, mooncw commented on member-api/src/test/java/com/kernelsquare/memberapi/domain/alert/controller/AlertControllerTest.java
> +            .andDo(document("alert-subscribe"));
andExpect할게  httpStatus 밖에 없는 듯한....?

2024-03-04 05:31 UTC, mooncw commented
지금 알림 엔티티에 데이터 속성을 추가했더니 비동기 부분에서 문제가 발생합니다.
현재 알림 저장하는 부분만 비동기 처리가 되어 알림 저장과 전송 서비스 부분과 일반 비지니스 로직과 분리가 완전하게 안되어있습니다.

2024-03-04 05:52 UTC, RossKWSang commented on core/src/main/java/com/kernelsquare/core/common_response/service/code/AlertServiceStatus.java
> +    MY_ALERT_ALL_FOUND(6100);
응답 상태 코드 수정이 필요해보입니다

뒤의 두자리 00부터 39까지는 예외처리입니다

2024-03-04 05:52 UTC, RossKWSang commented on core/src/main/java/com/kernelsquare/core/common_response/service/code/RankServiceStatus.java
> +
예외처리 중 가장 첫번째 번호이므로 00으로 고치셔야 할 것 같습니다.

2024-03-04 05:52 UTC, RossKWSang commented on domain-mongodb/src/main/java/com/kernelsquare/domainmongodb/domain/alert/entity/Alert.java
> +    }
해당 enum에서 description이 꼭 필요한가요?

2024-03-04 05:52 UTC, RossKWSang commented on domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/member_answer_vote/repository/MemberAnswerVoteReader.java
> +    Boolean existsByMemberIdAndAnswerId(Long memberId, Long answerId);
구현체에 적용된 Repository메서드와 특별히 다른점이 없다면 Repository메서드명을 그대로 쓰셔도 좋을 것 같습니다

2024-03-04 05:52 UTC, RossKWSang commented on domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/question/entity/Question.java
> +	}
이건 의견입니다면 updateClosedStatus보다 closeQuestion이 조금 더 명확한 의미이지 않을까 생각되네요

updateClosedStatus는 closedStatus를 deactivate하는 것도 포함시켜야 할 것 같아요

2024-03-04 05:52 UTC, RossKWSang commented on domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/rank/repository/RankReaderImpl.java
> +
repository를 rankRepository로 수정하는게 좋겠습니다

2024-03-04 05:52 UTC, RossKWSang commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/dto/AlertDto.java
> +        }
복수형일때 메서드명을 of로 사용하는 것을 알고있는데 틀린점이 있다면 확인 부탁드립니다

2024-03-04 05:52 UTC, RossKWSang commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/answer/facade/AnswerFacade.java
> +    }
개인적으로 Application 계층은 이런식으로 활용하는게 맞다고 봅니다

2024-03-04 05:52 UTC, RossKWSang commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/scheduler/manager/ScheculerManager.java
> +}
이런식으로 구현한 것은 좋아보입니다.

동작을 확인하셨나요?

2024-03-04 06:08 UTC, mooncw commented on domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/member_answer_vote/repository/MemberAnswerVoteReader.java
> +    Boolean existsByMemberIdAndAnswerId(Long memberId, Long answerId);
reader 메서드에는 용도를 좀 더 명확히 나타내는 것이 좋다고 생각하기에, 이대로 쓰면 정확히 어떤 기능을 하는지 잘 모를 것 같습니다.

2024-03-04 06:14 UTC, mooncw commented on domain-mongodb/src/main/java/com/kernelsquare/domainmongodb/domain/alert/entity/Alert.java
> +    }
현재는 필요 없을 것 같네요.

2024-03-04 06:16 UTC, mooncw commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/scheduler/manager/ScheculerManager.java
> +}
네 정상 작동합니다

2024-03-04 07:22 UTC, mooncw commented
> 지금 알림 엔티티에 데이터 속성을 추가했더니 비동기 부분에서 문제가 발생합니다. 현재 알림 저장하는 부분만 비동기 처리가 되어 알림 저장과 전송 서비스 부분과 일반 비지니스 로직과 분리가 완전하게 안되어있습니다.

해결은 했습니다만... 코드가 이게 맞는지 모르겠네요

2024-03-04 09:14 UTC, fingersdanny commented
....???????????????????????? 왜 flyway.. 2.1이 두개......

2024-03-04 09:49 UTC, fingersdanny commented on core/src/main/java/com/kernelsquare/core/util/ImageUtils.java
이전부터 들었던 의문인데... 이거 꼭 Component일 필요가 있을까요?? 내부 메서드들을 보면 다 정적 메서드라 실제로 클래스를 만들지 않아도 호출할 수 있고 그 말인 즉슨.. 빈에 등록하지 않아도 이 메서드들은 호출이 가능한데 Component로 등록하신 이유가 있을까요?

2024-03-04 10:06 UTC, mooncw commented on core/src/main/java/com/kernelsquare/core/util/ImageUtils.java
`@value`로 데이터를 받아오려면 필요한 걸로 알고 있습니다.

2024-03-04 10:17 UTC, fingersdanny commented on domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/member_answer_vote/repository/MemberAnswerVoteReader.java
> +    Boolean existsByMemberIdAndAnswerId(Long memberId, Long answerId);
메서드가 하려고 하는 일에 대한 설명을 남겨주시면 한 번 고민해보겠습니다

2024-03-04 11:30 UTC, fingersdanny requested changes
``@Async`` 어노테이션을 사용하면 로깅과 예외처리를 따로 해야한다고 알고 있는데 현재 올려주신 PR에서는 확인할 수 없는 것 같습니다.

기능을 개발해도 해당 기능에 대한 에러와 추적할 수 있는 장치가 없다면 추후에 문제가 발생했을 때 확인하기 힘들어질 수 밖에 없습니다. 

위와 같은 비동기 메서드에 대해서 어떤 식으로 예외처리나 로깅을 해야할지 한번 함께 고민해봅시다! 😄 

그 외의 내용들은 코멘트 참고해 주세요

2024-03-04 11:30 UTC, fingersdanny commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/mapper/AlertDtoMapper.java
> +    default String mapMemberId(MemberAdapter memberAdapter) {
접근 제어자를 default로 하신 이유가 있을까요..? Java에서는 기본적으로 따로 접근 제어자를 지정하지 않으면 default로 처리한다고 알고 있는데 명시하신 이유가 있는지 궁금합니다.

2024-03-04 11:30 UTC, fingersdanny commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/mapper/AlertMessageMapper.java
Mapstruct를 사용하지 않고 이처럼 구현하신 이유가 지연 로딩 때문일까요?

2024-03-04 11:30 UTC, fingersdanny commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/answer/mapper/AnswerDtoMapper.java
> +}
default..?

2024-03-04 11:46 UTC, mooncw commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/dto/RankAnswerAlertMessage.java
> +            .senderId("system")
답변을 매긴 후 랭킹에 든 답변 작성자에게 알림을 보내는 주체가 배치 시스템이기 때문에 system으로 했습니다.

2024-03-04 11:49 UTC, mooncw commented on domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/rank/entity/Rank.java
> +
제가 이번에 추가한 것입니다.

2024-03-04 11:51 UTC, mooncw commented on member-api/src/main/java/com/kernelsquare/memberapi/common/config/KafkaProducerConfig.java
> +	public ProducerFactory<String, Object> producerFactory() {
여러 가지 타입의 객체를 받기 위해서입니다.
물론 지금은 1개만 쓰게 되었지만요...

2024-03-04 11:54 UTC, mooncw commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/mapper/AlertMessageMapper.java
그렇다기보단 제가 원하는 엔티티로 받아올 수가 없어서 따로 작성하게 되었습니다.
ex) questionId로 question을 매핑
혹시 방법을 아신다면 알려주십셔

2024-03-04 12:00 UTC, mooncw commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/mapper/AlertDtoMapper.java
> +    default String mapMemberId(MemberAdapter memberAdapter) {
default를 안쓰면 에러가 뜹니다.
MapStruct는 매핑할 대상에 대한 메서드를 생성하는데, 이때 인터페이스의 메서드를 모두 확인하고 대상 클래스에 해당하는 메서드를 찾아 매핑 로직을 생성합니다.
default로 선언되어 있지 않으면 이 메서드에 대한 매핑 로직이 생성되지 않아서 에러가 발생합니다.

2024-03-04 12:19 UTC, mooncw commented on domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/member_answer_vote/repository/MemberAnswerVoteReader.java
> +    Boolean existsByMemberIdAndAnswerId(Long memberId, Long answerId);
원상님에게 여쭤보려했지만....
findByMemberIdAndAnswerId, existsByMemberIdAndAnswerId 둘 모두 본인이 해당 답변이 투표했지는 확인하는 기능을 합니다.
차이점은 findByMemberIdAndAnswerId는 Optional<MemberAnswerVote>를 리턴하고,
existsByMemberIdAndAnswerId는 Boolean을 리턴합니다.

2024-03-05 01:04 UTC, fingersdanny commented on domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/member_answer_vote/repository/MemberAnswerVoteReader.java
> +    Boolean existsByMemberIdAndAnswerId(Long memberId, Long answerId);
그러면 리턴 값이 다른 비슷한 두 개의 메서드가 필요한 경우가 어디일까요??

2024-03-05 01:06 UTC, fingersdanny commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/dto/RankAnswerAlertMessage.java
> +            .senderId("system")
일단 아래와 같이 상수 분리해서 사용하는 것도 좋아보이고 아직 이름에 대해서는 더 같이 고민해보죠
``` java
private final String SYSTEM_SENDER_ID = "system"
```

2024-03-05 01:25 UTC, Hju95 commented on domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/answer/repository/AnswerReader.java
> +}
숫자가 더 좋아보여요 읽기도 쉽고 익숙하네요

2024-03-05 01:31 UTC, Hju95 commented on domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/answer/repository/AnswerReaderImpl.java
> +        return answerRepository.findAnswersByQuestionIdSortedByCreationDate(questionId);
CreationDate 가 아니고 createddate 아닌가요?

2024-03-05 01:59 UTC, mooncw commented on domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/answer/repository/AnswerReaderImpl.java
> +        return answerRepository.findAnswersByQuestionIdSortedByCreationDate(questionId);
answerRepository 보시면,
@Query("SELECT a FROM Answer a WHERE a.question.id = :questionId ORDER BY a.createdDate DESC")
List<Answer> findAnswersByQuestionIdSortedByCreationDate(@Param("questionId") Long questionId);
로 작성되어있습니다.

2024-03-05 02:11 UTC, Hju95 commented on domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/level/repository/LevelReader.java
> +    Level findLevelOtherThanId(Long levelName, Long levelId);
좀 더 직관적이게 메서드명을 수정해야할 것 같습니다.
딱 보고 무슨 기능을 하는지 아는 게 아니고 추측을 해야하는 것 같아요
@mooncw @fingersdanny @RossKWSang

2024-03-05 02:23 UTC, Hju95 commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/dto/RankAnswerAlertMessage.java
> +            .senderId("system")
`alertBatchSystem`  혹은 그냥 `BatchSystem` 이 좋은 것 같습니다

2024-03-06 07:15 UTC, mooncw commented on domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/question/entity/Question.java
> +	}
closeQuestion로 수정했습니다.

2024-03-06 07:15 UTC, mooncw commented on domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/rank/repository/RankReaderImpl.java
> +
반영했습니다.

2024-03-06 07:36 UTC, RossKWSang commented on domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/level/repository/LevelReader.java
> +    Level findLevelOtherThanId(Long levelName, Long levelId);
이 코드가 어떤 동작하는지는 알겠는데 ~

Reader에 있음과 예외를 일으키는 이유가 어떻게 되나요?

2024-03-06 09:49 UTC, fingersdanny requested changes

2024-03-07 07:02 UTC, mooncw commented on domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/member_answer_vote/repository/MemberAnswerVoteReader.java
> +    Boolean existsByMemberIdAndAnswerId(Long memberId, Long answerId);
그대로 사용하겠습니다.

2024-03-07 07:03 UTC, mooncw commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/dto/RankAnswerAlertMessage.java
> +            .senderId("system")
public static final String ALERT_SYSTEM = "scheduler_manager";로 만들어 사용했습니다.

2024-03-07 07:05 UTC, mooncw commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/mapper/AlertMessageMapper.java
저번에 병룡님이 말씀해주신 MapStruct를 사용하는 방향으로 수정했습니다.
확인해주세욧!

2024-03-07 07:09 UTC, fingersdanny approved these changes

2024-03-07 07:11 UTC, fingersdanny commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/answer/mapper/AnswerDtoMapper.java
👍🏻

2024-03-07 07:15 UTC, mooncw commented on domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/answer/repository/AnswerReader.java
> +}
현재 Reader에까지 그 기준을 보여줄 필요가 없다고 생각하긴 했습니다만.. 다른 분들 생각은 어떠신지요

2024-03-07 07:17 UTC, mooncw commented on domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/level/repository/LevelReader.java
> +    Level findLevelOtherThanId(Long levelName, Long levelId);
제 기억으론 변경하고자 하는 level이 존재하는지 알기 위한 로직으로 알고 있습니다.

2024-03-07 07:19 UTC, mooncw commented on member-api/src/main/java/com/kernelsquare/memberapi/common/config/AsyncConfig.java
> +    }
입력 값에 대한 의견이 있으시면 주십셔

2024-03-07 07:28 UTC, mooncw commented
> `@Async` 어노테이션을 사용하면 로깅과 예외처리를 따로 해야한다고 알고 있는데 현재 올려주신 PR에서는 확인할 수 없는 것 같습니다.
> 
> 기능을 개발해도 해당 기능에 대한 에러와 추적할 수 있는 장치가 없다면 추후에 문제가 발생했을 때 확인하기 힘들어질 수 밖에 없습니다.
> 
> 위와 같은 비동기 메서드에 대해서 어떤 식으로 예외처리나 로깅을 해야할지 한번 함께 고민해봅시다! 😄
> 
> 그 외의 내용들은 코멘트 참고해 주세요

성공 로깅은 기존 Logging 파일에 추가했고, 예외처리는 AsyncExceptionHandler를 만들어서 로깅을 합니다.

2024-03-07 07:28 UTC, Hju95 commented
> 지금 알림 엔티티에 데이터 속성을 추가했더니 비동기 부분에서 문제가 발생합니다. 현재 알림 저장하는 부분만 비동기 처리가 되어 알림 저장과 전송 서비스 부분과 일반 비지니스 로직과 분리가 완전하게 안되어있습니다.

요건 해결되신 걸까요? @mooncw

2024-03-07 07:39 UTC, Hju95 commented on domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/answer/repository/AnswerReader.java
> +}
병룡님 의견에도 동의합니다만 현재 답변에서 순위 매길 수 있는 부분은 투표 하나뿐이기에 
헷갈리지 않으니 위 처럼만 적어도 상관없지 않을까 싶습니다.

2024-03-07 07:40 UTC, Hju95 commented on domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/level/repository/LevelReader.java
> +    Level findLevelOtherThanId(Long levelName, Long levelId);
이 부분은 알림 PR과는 구분 짓는게 좋을 것 같아서 
수정하시게 된다해도 따로 PR 올려서 수정하는게 나을 것 같습니다.

2024-03-07 07:44 UTC, Hju95 commented on member-api/src/main/java/com/kernelsquare/memberapi/common/config/AsyncConfig.java
> +    }
해보고 문제 생기면 조정하면 될 듯 합니다

2024-03-07 07:47 UTC, Hju95 approved these changes

2024-03-07 07:48 UTC, merged