[feat] 기술 스택 모든 조회 기능 개발
Kernel360/f1-KernelSquare-backend pull request #36
Opened 2023-12-29 06:42 UTC by mooncw

## PR을 보내기 전에 확인해주세요!!
- [x] 컨벤션에 맞게 작성했습니다. 컨벤션 확인은 [여기](https://www.notion.so/3ab6391203024ffa8be3b414c511d60e?pvs=4)
- [x] 변경 사항에 대한 테스트를 했습니다.

## 관련 이슈
close: #26 

## 개요
> 기술 스택 모든 조회 기능을 구현하기 위함

## 상세 내용
- 단일 조회는 없음
- 현재 응답 메시지의 data는 기술 스택 이름만 List 형식으로 보내줌
- 추가적으로 service와 controller test 코드 스타일 수정(확인해주시고 의견이 있으시면 주세요)

2023-12-29 06:56 UTC, RossKWSang commented on src/main/java/com/kernel360/kernelsquare/domain/tech_stack/dto/FindAllTechStacksResponse.java
> +    }
record의 of 생성자를 꼭 쓰는 이유가 있나요?

생성자 메서드를 쓰지않고 of를 쓰는 이유가 궁금합니다.

2023-12-29 06:56 UTC, RossKWSang commented on src/test/java/com/kernel360/kernelsquare/domain/tech_stack/service/TechStackServiceTest.java
> +    @Mock
코딩 컨벤션에서 조금 변화가 보이는데요.

변화를 주신 기술적 이유를 말씀해주시거나, 레퍼런스를 주시면 감사하겠습니다.

2023-12-29 07:32 UTC, mooncw commented on src/main/java/com/kernel360/kernelsquare/domain/tech_stack/dto/FindAllTechStacksResponse.java
> +    }
통일성을 위해 of를 사용했습니다.

2023-12-29 08:08 UTC, RossKWSang approved these changes
LGTM

2023-12-29 08:12 UTC, mooncw commented on src/test/java/com/kernel360/kernelsquare/domain/tech_stack/service/TechStackServiceTest.java
> +    @Mock
service test는 service에 대해서만 테스트하고, controller test는 controller에 대해서만 테스트하기 위해서입니다.
물론 이렇게하면 repository에 대한 테스트 코드도 짜야합니다.

2024-01-02 02:49 UTC, fingersdanny commented on src/test/java/com/kernel360/kernelsquare/domain/tech_stack/service/TechStackServiceTest.java
> +        verify(techStackRepository,times(1)).findAll();
```java
//when
techStackService.findAllTechStacks();

//then
assertThat() .....

//verify
verify(techStackRepository, times(1)).findAll();
```

2024-01-02 02:49 UTC, fingersdanny commented on src/test/java/com/kernel360/kernelsquare/domain/tech_stack/service/TechStackServiceTest.java
> +        verify(techStackRepository,times(1)).findAll();
이런 식으로 변경하면 어떨까요?

2024-01-02 02:51 UTC, fingersdanny commented on src/test/java/com/kernel360/kernelsquare/domain/tech_stack/service/TechStackServiceTest.java
>  @SpringBootTest
요거 어노테이션 제거해도 테스트 돌아갑니당

2024-01-02 03:32 UTC, fingersdanny requested changes
comment 확인해주세요

2024-01-02 07:03 UTC, corazzon commented
LGTM :)

2024-01-02 07:04 UTC, fingersdanny approved these changes
제가 보기엔 좋은 것 같아요!

2024-01-02 07:05 UTC, Hju95 approved these changes

2024-01-02 07:08 UTC, merged