[feature] SEO 최적화를 위한 API (질문 & 모각코 리스트)
Kernel360/f1-KernelSquare-backend pull request #432
Opened 2024-03-19 09:03 UTC by RossKWSang

## PR을 보내기 전에 확인해주세요!!
- [x] 컨벤션에 맞게 작성했습니다. 컨벤션 확인은 [여기](https://www.notion.so/3ab6391203024ffa8be3b414c511d60e?pvs=4)
- [x] 변경 사항에 대한 테스트를 했습니다.

## 관련 이슈
close: #423

## 개요
> SEO 최적화를 위하여 전체 질문 id와 모각코 token 값을 리스트에 담아 반환하는 API를 만들었습니다.

## 상세 내용
- 자주 호출되는 API가 아니므로 향후 데이터가 쌓여 Load가 생길 경우 주기적으로 캐싱을 하거나 정책적으로 호출되는 양을 정하도록 합니다.
- API 명세는 각각 다음과 같습니다.
  - [질문](https://www.notion.so/SEO-4d20389a676c41b09938899fb91cb57a)
  - [모각코](https://www.notion.so/SEO-3da01f10e49d45f2b83e016dffd4b6d7)

2024-03-19 10:03 UTC, RossKWSang commented on domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/coding_meeting/service/CodingMeetingServiceImpl.java
> +    @Cacheable(cacheNames = "coding_meeting_list")
Redis가 있는 DataHub 서버에 캐싱하는건데

지금은 사용하지 않을 예정이니 삭제하겠습니다

2024-03-19 12:57 UTC, mooncw approved these changes

2024-03-19 13:16 UTC, fingersdanny commented on member-api/src/main/java/com/kernelsquare/memberapi/common/config/RedisConfig.java
> +import java.time.Duration;
쓰지 않는 Import문인 것 같습니다.

2024-03-19 13:23 UTC, fingersdanny commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/question/controller/QuestionController.java
> +
[일급 컬렉션](https://jojoldu.tistory.com/412)을 사용해보면 어떨까요..?

2024-03-19 13:26 UTC, fingersdanny commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/question/service/QuestionService.java
>  import org.springframework.transaction.annotation.Transactional;
Import문 정리가 필요해 보입니다.

2024-03-19 13:27 UTC, fingersdanny commented on member-api/src/test/java/com/kernelsquare/memberapi/domain/coding_meeting/controller/CodingMeetingControllerTest.java
> +        String token02 = TokenGenerator.randomCharacterWithPrefix(TEST_CODING_MEETING_TOKEN_PREFIX);
토큰은 그냥 랜덤 문자열로 만들어서 테스트 작성해도 될것 같습니다.

2024-03-19 13:30 UTC, fingersdanny commented on member-api/src/test/java/com/kernelsquare/memberapi/domain/question/controller/QuestionControllerTest.java
왜 위의 CodingMeetingController에는 RestDocs 사용하시고 아래는 그냥 테스트를 작성하셨을까요?

2024-03-19 13:30 UTC, fingersdanny requested changes
comment 확인 부탁드려요

2024-03-20 02:17 UTC, RossKWSang commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/question/controller/QuestionController.java
> +
### 일급 컬렉션을 사용하는 이유

1. 비즈니스 로직에 걸맞는 자료구조 생성 - 가독성
2. 컬렉션의 불변성 - final은 재할당만 금지하므로 컬렉션에 값을 추가하는 것을 막을 수 없음
3. 상태와 로직을 한곳에서 관리
4. 컬렉션을 기반으로 한 용어 사용과 검색이 가능

2024-03-20 02:18 UTC, RossKWSang commented on member-api/src/test/java/com/kernelsquare/memberapi/domain/question/controller/QuestionControllerTest.java
테스트 코드는 다 지우고 커밋하겠습니다

2024-03-20 02:18 UTC, RossKWSang commented on member-api/src/test/java/com/kernelsquare/memberapi/domain/coding_meeting/controller/CodingMeetingControllerTest.java
> +                        document("coding-meetings/seo", getDocumentResponse(),
테스트 코드는 다 지우고 커밋하겠습니다

2024-03-20 03:24 UTC, Hju95 commented on core/src/main/java/com/kernelsquare/core/common_response/service/code/QuestionServiceStatus.java
> +	QUESTION_SEO_LIST_FOUND(2155);
2145 로 바꿔주세요

2024-03-20 03:38 UTC, Hju95 approved these changes

2024-03-20 05:14 UTC, RossKWSang commented on core/src/main/java/com/kernelsquare/core/common_response/service/code/QuestionServiceStatus.java
> +	QUESTION_SEO_LIST_FOUND(2155);
바꿨습니다

2024-03-20 05:54 UTC, RossKWSang commented on member-api/src/test/java/com/kernelsquare/memberapi/domain/coding_meeting/controller/CodingMeetingControllerTest.java
> +        String token02 = TokenGenerator.randomCharacterWithPrefix(TEST_CODING_MEETING_TOKEN_PREFIX);
랜덤 문자열로 바꿨습니다

2024-03-20 05:54 UTC, RossKWSang commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/question/service/QuestionService.java
>  import org.springframework.transaction.annotation.Transactional;
정리했습니다

2024-03-20 05:54 UTC, RossKWSang commented on member-api/src/main/java/com/kernelsquare/memberapi/common/config/RedisConfig.java
> +import java.time.Duration;
지웠습니다

2024-03-20 06:20 UTC, RossKWSang commented on member-api/src/test/java/com/kernelsquare/memberapi/domain/question/controller/QuestionControllerTest.java
Question 전체 조회 API에 대한 테스트 코드 Rest Docs 형식으로 재작성했습니다

2024-03-21 01:30 UTC, fingersdanny commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/tech_stack/dto/FindAllTechStacksResponse.java
> +public record   FindAllTechStacksResponse(
띄어쓰기가 이상한거 같아요

2024-03-21 01:31 UTC, fingersdanny commented on member-api/src/test/java/com/kernelsquare/memberapi/domain/coding_meeting/controller/CodingMeetingControllerTest.java
> +								)
라인 수정 부탁드려요 (들여쓰기..)

2024-03-21 01:31 UTC, fingersdanny commented on member-api/src/test/java/com/kernelsquare/memberapi/domain/question/controller/QuestionControllerTest.java
> +										fieldWithPath("data.question_id_list[].question_id").type(JsonFieldType.NUMBER).description("질문 아이디")
라인 수정 부탁드려요 (들여쓰기).

2024-03-21 01:32 UTC, fingersdanny reviewed
코멘트 확인해 주세요~

2024-03-21 05:59 UTC, RossKWSang reviewed
@fingersdanny 들여쓰기 바뀐것 확인 부탁드립니다

2024-03-21 06:28 UTC, fingersdanny approved these changes
고생하셨습니다.

2024-03-21 06:28 UTC, merged