[refactor] alert-api 서버 모듈 추가
Kernel360/f1-KernelSquare-backend pull request #433
Opened 2024-03-19 09:15 UTC by mooncw

## PR을 보내기 전에 확인해주세요!!
- [x] 컨벤션에 맞게 작성했습니다. 컨벤션 확인은 [여기](https://www.notion.so/3ab6391203024ffa8be3b414c511d60e?pvs=4)
- [x] 변경 사항에 대한 테스트를 했습니다.

## 관련 이슈
close: #430 

## 개요
> member-api 스프링부트 서버들끼리 알림 데이터를 공유하기 위해 기존 알림 기능을 alert-api 모듈로 분리하기 위함

## 상세 내용
- `@AuthenticationPrincipal`를 사용하는데 필요한 파일은 가져옴
- kafka를 이용하여 member-api로부터 이벤트를 받음
- 서로 다른 그룹인 2개의 kafka listener를 사용하여 알림을 저장하는 로직과 클라이언트에게 보내는 로직 분리
- member-api와 alert를 각각의 Dockerfile로 빌드함
- 추가된 alert Dockerfile로 인한 cd 워크플로우 수정
- pr이 승인되면 ec2 인스턴스들의 docker-compose.yml 파일 수정할 예정

2024-03-19 13:34 UTC, fingersdanny commented on .github/workflows/cd.yml
> +          aws ec2 revoke-security-group-ingress --group-name ${{ secrets.AWS_SG_NAME }} --protocol tcp --port 8503 --cidr ${{ steps.ip.outputs.ipv4 }}/32
요거는 어디에 쓰는 포트번호인가요?

2024-03-19 13:39 UTC, mooncw commented on .github/workflows/cd.yml
> +          aws ec2 revoke-security-group-ingress --group-name ${{ secrets.AWS_SG_NAME }} --protocol tcp --port 8503 --cidr ${{ steps.ip.outputs.ipv4 }}/32
알림 서버 포트번호입니다.

2024-03-19 13:41 UTC, fingersdanny commented on alert-api/src/test/java/com/kernelsquare/alertapi/domain/alert/controller/AlertControllerTest.java
> +                .with(SecurityMockMvcRequestPostProcessors.user(memberAdapter))
왜 앞의 클래스 붙도록 변경하셨을까요..? 다른 테스트는 다 ``user()`` 이렇게 되어있어요..

2024-03-19 13:41 UTC, fingersdanny commented on alert-api/src/test/java/com/kernelsquare/alertapi/domain/alert/controller/AlertControllerTest.java
> +                    PayloadDocumentation.fieldWithPath("data.personal_alert_list[].alert_type").type(JsonFieldType.STRING).description("알림 타입"),
위랑 마찬가지로 class를 붙인 이유가 있으신가요..?

2024-03-19 13:42 UTC, fingersdanny requested changes
comment 확인 부탁드려요~

2024-03-19 13:46 UTC, mooncw commented on alert-api/src/test/java/com/kernelsquare/alertapi/domain/alert/controller/AlertControllerTest.java
> +                .with(SecurityMockMvcRequestPostProcessors.user(memberAdapter))
오잉? 저 옮기기만 했는데 저렇게 되어 있었.....

2024-03-19 13:47 UTC, mooncw commented on alert-api/src/test/java/com/kernelsquare/alertapi/domain/alert/controller/AlertControllerTest.java
> +                    PayloadDocumentation.fieldWithPath("data.personal_alert_list[].alert_type").type(JsonFieldType.STRING).description("알림 타입"),
아무래도 옮기면서 저렇게 변했나봐요..
안그래도 저거 보면서 언제 저렇게 변경하셨지? 했는데, 제가 범인이였군요 ㅋㅋ...

2024-03-19 13:50 UTC, mooncw commented on alert-api/src/test/java/com/kernelsquare/alertapi/domain/alert/controller/AlertControllerTest.java
> +                .with(SecurityMockMvcRequestPostProcessors.user(memberAdapter))
아래 리뷰 포함해서 변한거 전부 원래대로 바꾸겠습니다!

2024-03-19 14:28 UTC, mooncw commented on alert-api/src/test/java/com/kernelsquare/alertapi/domain/alert/controller/AlertControllerTest.java
> +                .with(SecurityMockMvcRequestPostProcessors.user(memberAdapter))
다시 원래대로 바꿨습니다!

2024-03-20 03:08 UTC, mooncw commented
리뷰 가능 하십니까?
@fingersdanny

2024-03-20 03:22 UTC, Hju95 approved these changes

2024-03-20 05:32 UTC, mooncw commented
알림 서버는 관리자 인스턴스 서버에 옮기기로 했습니다!
- 관리자 인스턴스 서버도 서브도메인이 생겨서 https으로 통신이 가능함에 따라 블루 그린 인스턴스 서버와 분리하여 서비스 가능
- 블루 그린 인스턴스 서버와 분리함에 따라 무중단 배포와 상관없이 SSE 연결을 유지할 수 있음

@fingersdanny

2024-03-20 10:56 UTC, mooncw commented
다시 리뷰 해주세요!
@fingersdanny  @Hju95 @RossKWSang

2024-03-21 01:25 UTC, RossKWSang approved these changes

2024-03-21 01:37 UTC, fingersdanny approved these changes
LGTM

2024-03-21 05:47 UTC, Hju95 approved these changes

2024-03-21 05:47 UTC, merged