[feat] 닉네임 변경 기능 추가
Kernel360/f1-KernelSquare-backend pull request #435
Opened 2024-03-20 09:45 UTC by Hju95

## PR을 보내기 전에 확인해주세요!!
- [x] 컨벤션에 맞게 작성했습니다. 컨벤션 확인은 [여기](https://www.notion.so/3ab6391203024ffa8be3b414c511d60e?pvs=4)
- [x] 변경 사항에 대한 테스트를 했습니다.

## 관련 이슈
close: #431 

## 개요
> 닉네임 수정 기능 추가

## 상세 내용
- 닉네임 수정 기능 추가
- 닉네임 중복 체크 로직 추가
- UpdateMemberNicknameRequest 에서 member_id 는 현재 프론트와 admin API 명세서 따라서 작성됨
- 테스트 코드 작성 및 Rest Doc 작성

++ CORS dev 도메인 추가

2024-03-20 09:48 UTC, RossKWSang approved these changes

2024-03-20 10:47 UTC, fingersdanny commented
Test 수정해주세요~

2024-03-20 10:47 UTC, fingersdanny requested changes
테스트.. 수정해주세요

2024-03-21 03:32 UTC, fingersdanny commented on member-api/src/main/java/com/kernelsquare/memberapi/common/config/SecurityConfig.java
> +			.requestMatchers(HttpMethod.PUT, "/api/v1/members/nick").hasRole("USER")
``"/api/v1/members/nickname"`` 로 수정해주세요

2024-03-21 03:32 UTC, fingersdanny commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/member/dto/UpdateMemberNicknameRequest.java
비속어 필터 넣어주세요

2024-03-21 03:37 UTC, Hju95 commented on member-api/src/main/java/com/kernelsquare/memberapi/common/config/SecurityConfig.java
> +			.requestMatchers(HttpMethod.PUT, "/api/v1/members/nick").hasRole("USER")
매의 눈 이시군요 반영했습니다~

2024-03-21 03:37 UTC, Hju95 commented on member-api/src/main/java/com/kernelsquare/memberapi/domain/member/dto/UpdateMemberNicknameRequest.java
반영 완료했습니다

2024-03-21 03:37 UTC, mooncw commented on member-api/src/test/java/com/kernelsquare/memberapi/domain/member/service/MemberServiceTest.java
> +		assertThat(optionalFoundMember.get().getNickname()).isEqualTo(newNickname);
흠...

2024-03-21 03:38 UTC, Hju95 commented on member-api/src/test/java/com/kernelsquare/memberapi/domain/member/service/MemberServiceTest.java
> +		assertThat(optionalFoundMember.get().getNickname()).isEqualTo(newNickname);
냐흠냐....

2024-03-21 05:06 UTC, fingersdanny approved these changes

2024-03-21 05:06 UTC, merged